/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationRequestDto
 */
export interface CreateOrganizationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequestDto
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequestDto
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequestDto
     */
    organizationIDFileLink: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequestDto
     */
    governmentIDFileLink: string;
}

/**
 * Check if a given object implements the CreateOrganizationRequestDto interface.
 */
export function instanceOfCreateOrganizationRequestDto(value: object): value is CreateOrganizationRequestDto {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('organizationIDFileLink' in value) || value['organizationIDFileLink'] === undefined) return false;
    if (!('governmentIDFileLink' in value) || value['governmentIDFileLink'] === undefined) return false;
    return true;
}

export function CreateOrganizationRequestDtoFromJSON(json: any): CreateOrganizationRequestDto {
    return CreateOrganizationRequestDtoFromJSONTyped(json, false);
}

export function CreateOrganizationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequestDto {
    if (json == null) {
        return json;
    }
    return {

        'domain': json['domain'],
        'organizationName': json['organizationName'],
        'organizationIDFileLink': json['organizationIDFileLink'],
        'governmentIDFileLink': json['governmentIDFileLink'],
    };
}

export function CreateOrganizationRequestDtoToJSON(json: any): CreateOrganizationRequestDto {
    return CreateOrganizationRequestDtoToJSONTyped(json, false);
}

export function CreateOrganizationRequestDtoToJSONTyped(value?: CreateOrganizationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'domain': value['domain'],
        'organizationName': value['organizationName'],
        'organizationIDFileLink': value['organizationIDFileLink'],
        'governmentIDFileLink': value['governmentIDFileLink'],
    };
}

