/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCertDto
 */
export interface CreateCertDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCertDto
     */
    domain: string;
}

/**
 * Check if a given object implements the CreateCertDto interface.
 */
export function instanceOfCreateCertDto(value: object): value is CreateCertDto {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function CreateCertDtoFromJSON(json: any): CreateCertDto {
    return CreateCertDtoFromJSONTyped(json, false);
}

export function CreateCertDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCertDto {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
    };
}

  export function CreateCertDtoToJSON(json: any): CreateCertDto {
      return CreateCertDtoToJSONTyped(json, false);
  }

  export function CreateCertDtoToJSONTyped(value?: CreateCertDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
    };
}

