/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrchestratorDto
 */
export interface CreateOrchestratorDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrchestratorDto
     */
    label: string;
}

/**
 * Check if a given object implements the CreateOrchestratorDto interface.
 */
export function instanceOfCreateOrchestratorDto(value: object): value is CreateOrchestratorDto {
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function CreateOrchestratorDtoFromJSON(json: any): CreateOrchestratorDto {
    return CreateOrchestratorDtoFromJSONTyped(json, false);
}

export function CreateOrchestratorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrchestratorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
    };
}

  export function CreateOrchestratorDtoToJSON(json: any): CreateOrchestratorDto {
      return CreateOrchestratorDtoToJSONTyped(json, false);
  }

  export function CreateOrchestratorDtoToJSONTyped(value?: CreateOrchestratorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
    };
}

