/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDeviceDto
 */
export interface CreateDeviceDto {
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    label: string;
}

/**
 * Check if a given object implements the CreateDeviceDto interface.
 */
export function instanceOfCreateDeviceDto(value: object): value is CreateDeviceDto {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function CreateDeviceDtoFromJSON(json: any): CreateDeviceDto {
    return CreateDeviceDtoFromJSONTyped(json, false);
}

export function CreateDeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeviceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'key': json['key'],
        'roomId': json['roomId'],
        'label': json['label'],
    };
}

  export function CreateDeviceDtoToJSON(json: any): CreateDeviceDto {
      return CreateDeviceDtoToJSONTyped(json, false);
  }

  export function CreateDeviceDtoToJSONTyped(value?: CreateDeviceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'key': value['key'],
        'roomId': value['roomId'],
        'label': value['label'],
    };
}

