/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRoomDto
 */
export interface CreateRoomDto {
    /**
     * 
     * @type {string}
     * @memberof CreateRoomDto
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRoomDto
     */
    description: string;
}

/**
 * Check if a given object implements the CreateRoomDto interface.
 */
export function instanceOfCreateRoomDto(value: object): value is CreateRoomDto {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateRoomDtoFromJSON(json: any): CreateRoomDto {
    return CreateRoomDtoFromJSONTyped(json, false);
}

export function CreateRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'description': json['description'],
    };
}

  export function CreateRoomDtoToJSON(json: any): CreateRoomDto {
      return CreateRoomDtoToJSONTyped(json, false);
  }

  export function CreateRoomDtoToJSONTyped(value?: CreateRoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'description': value['description'],
    };
}

