/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrchestratorVerifyLicenseDto
 */
export interface OrchestratorVerifyLicenseDto {
    /**
     * 
     * @type {string}
     * @memberof OrchestratorVerifyLicenseDto
     */
    key: string;
}

/**
 * Check if a given object implements the OrchestratorVerifyLicenseDto interface.
 */
export function instanceOfOrchestratorVerifyLicenseDto(value: object): value is OrchestratorVerifyLicenseDto {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function OrchestratorVerifyLicenseDtoFromJSON(json: any): OrchestratorVerifyLicenseDto {
    return OrchestratorVerifyLicenseDtoFromJSONTyped(json, false);
}

export function OrchestratorVerifyLicenseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrchestratorVerifyLicenseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

  export function OrchestratorVerifyLicenseDtoToJSON(json: any): OrchestratorVerifyLicenseDto {
      return OrchestratorVerifyLicenseDtoToJSONTyped(json, false);
  }

  export function OrchestratorVerifyLicenseDtoToJSONTyped(value?: OrchestratorVerifyLicenseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

