/* tslint:disable */
/* eslint-disable */
/**
 * Platform Healthcare API
 * The Platform Healthcare API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDeviceDto
 */
export interface UpdateDeviceDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    roomId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    label?: string;
}

/**
 * Check if a given object implements the UpdateDeviceDto interface.
 */
export function instanceOfUpdateDeviceDto(value: object): value is UpdateDeviceDto {
    return true;
}

export function UpdateDeviceDtoFromJSON(json: any): UpdateDeviceDto {
    return UpdateDeviceDtoFromJSONTyped(json, false);
}

export function UpdateDeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDeviceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'] == null ? undefined : json['deviceId'],
        'key': json['key'] == null ? undefined : json['key'],
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

  export function UpdateDeviceDtoToJSON(json: any): UpdateDeviceDto {
      return UpdateDeviceDtoToJSONTyped(json, false);
  }

  export function UpdateDeviceDtoToJSONTyped(value?: UpdateDeviceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'key': value['key'],
        'roomId': value['roomId'],
        'label': value['label'],
    };
}

